<?php
require_once("../database/connectionManager.php");

/**
 * @OA\Schema()
 */
class Clients
{
	/**
	 * The unique, autogenerated, identifier of the client.
	 * @var integer
	 * @OA\Property()
	 */
	private $clientID;

	/**
	 * The full name of the client.
	 * @var string
	 * @OA\Property()
	 */
	private $clientName;

	/**
	 * The License Number of the client.
	 * @var string
	 * @OA\Property()
	 */
	private $licenseNumber;

	/**
	 * The start date of the license.
	 * @var string
	 * @OA\Property()
	 */
	private $licenseStartDate;

	/**
	 * The expiry date of the license.
	 * @var string
	 * @OA\Property()
	 */
	private $licenseEndDate;

	/**
	 * The client's license key.
	 * @var string
	 * @OA\Property()
	 */
	private $licenseKey;

	private $connectionManager;
	private $dbConnection;

	function __construct()
	{
		$this->connectionManager = new ConnectionManager();
		$this->dbConnection = $this->connectionManager->getConnection();
	}

	function getAllClients()
	{
		$query = "SELECT * FROM clients";

		$statement = $this->dbConnection->prepare($query);

		$statement->execute();

		return $statement->fetchAll(PDO::FETCH_ASSOC);
	}

	function getClientByID($clientID)
	{
		$query = "SELECT * FROM clients WHERE client_id = " . $clientID;

		$statement = $this->dbConnection->prepare($query);

		$statement->execute();

		return $statement->fetch(PDO::FETCH_ASSOC);
	}

	function getClientByLicenseKey($licenseKey)
	{
		$query = "SELECT client_id FROM clients WHERE licenseKey = :licenseKey";

		$statement = $this->dbConnection->prepare($query);

		$statement->execute(['licenseKey' => $licenseKey]);

		return $statement->fetch(PDO::FETCH_ASSOC);
	}
}
